### ISSUE TITLE
Make raw optional on getList

### ISSUE THREAD

**Issue by LucusWebsites** [nicgirault/express-crud-router#57]
I have sequelize afterFind hooks which rely on the instance.get('propertyName') method to read a proprety value.
The hooks work fine except on the getList call.

Turns out the raw: true line caused this:
https://github.com/lalalilo/express-sequelize-crud/blob/master/src/sequelize/index.ts#L24

An option for example like this would be very helpfull:

```js
app.use(
  crud('/admin/users', sequelizeCrud(User), {
    getListRaw: false
  })
)

**Comment by nicgirault** [comment]
If this is still an issue, could you open an issue on https://github.com/nicgirault/express-crud-router-sequelize-v6-connector as the crud logic and the orm logic are now separated? Thanks
