### ISSUE TITLE
TypeError: crud is not a function

### ISSUE THREAD

**Issue by AntoniBasa** [nicgirault/express-crud-router#74]
i tried but it doesn't work((
please fix

**Comment by alixq** [comment]
Please print the code that fails here

**Comment by ZvNico** [comment]
I don't get either why i got "crud" not a function"

`const crud = require("express-crud-router")
const {User} = require("./../models")
const sequelizeCrud = require("./crud")(User)

crud("/api/users", {
    ...sequelizeCrud
})`

**Comment by Paylign** [comment]
For me I change it to ````const { crud } = require("express-crud-router")```` and the error went away
