### ISSUE TITLE
implement FakeRest filters

### ISSUE THREAD

**Issue by fblinks** [nicgirault/express-crud-router#91]
Hi, 
I want to implement filters like the ones exposed by [FakeRest](https://github.com/marmelab/FakeRest#supported-filters), that should be the [dialect used by React Admin Simple Rest Data Provider](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-simple-rest#rest-dialect).
For example, if I pass the filter `{"id_gt":100}` I would like to have a query such as 
```SQL
SELECT * from x WHERE id > 100;
```

while now I get something like: 
```SQL
SELECT * from x WHERE id_gt = 100;
```

I'm not sure where and how I should implement those kind of filters

**Comment by nicgirault** [comment]
You can handle the logic in the `get` action:

```js
app.use(
  crud('/admin/users', {
    get: ({ filter, limit, offset, order }) =>
      // do whatever you need with filter here
  })
)
```
